export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILED = 'GET_USER_FAILED'

export const DEL_USER_REQUEST = 'DEL_USER_REQUEST'
export const DEL_USER_SUCCESS = 'DEL_USER_SUCCESS'
export const DEL_USER_FAILED = 'DEL_USER_FAILED'

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAILED = 'ADD_USER_FAILED'

export const GETONE_USER_REQUEST = 'GETONE_USER_REQUEST'
export const GETONE_USER_SUCCESS = 'GETONE_USER_SUCCESS'
export const GETONE_USER_FAILED = 'GETONE_USER_FAILED'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED'
